### ISSUE TITLE
No page returned under Ubuntu 18.04

### ISSUE THREAD

**Issue by WJDigby** [SecurityRiskAdvisors/VECTR#7]
@thebleucheese Trying VECTR following your post at unfetter.

Appears to build successfully after running the docker-compose command, but when I browse to the URI listed in the readme (http://your_docker_host:8081/sra-purpletools-webui/app) a server appears to be listening but no data or page is returned. Unfortunately I did not save the output of the docker-compose command.

Do you have a recommended linux distro and version to run this under?

**Comment by carlvonderheid** [comment]
@WJDigby This is more than likely a documentation issue.  Our docker-compose file assumes that you've put the install package under /opt/vectr.  We will make this clear in the future.

You can change this location by replacing the host portion of the volume declarations.  If you open up the docker-compose.yml file, and you installed vectr under /tmp/ceTest, just replace the host portion of the volume declarations:
---
version: '2'

services:
  mongo:
    volumes:
      - /tmp/ceTest/dumpfiles:/opt/vectr/dumpfiles

  tomcat:
    volumes:
      - /tmp/ceTest/ce_4.3.0_20180512/wars:/usr/local/tomcat/webapps/
      - /tmp/ceTest/ce_4.3.0_20180512/config:/usr/local/tomcat/app_conf
      - /tmp/ceTest/ce_4.3.0_20180512/backup:/opt/vectr/backup/
      - /tmp/ceTest/ce_4.3.0_20180512/migrationlogs:/opt/vectr/migrationlogs/
      - /tmp/ceTest/ce_4.3.0_20180512/migrationbackups:/opt/vectr/migrationbackups

Let us know how it goes.

**Comment by thebleucheese** [comment]
I think we missed one more step in the last release notes.  For the mongo container It's expecting a directory at /var/data/sandbox1 too based on dev.yml.  That directory will need to exist if we want the data to persist by default.

**Comment by c0rndogs** [comment]
I'm having the same problem.  Mine is all default install.  Everything in /opt/vectr is as it should be, presumably, but I get a page cannot be found when I browse to the URI.  Nmap says the port is open.

**Comment by carlvonderheid** [comment]
On the host, do you see any directories under /opt/vectr/wars/, or just .war files?

**Comment by c0rndogs** [comment]
There is a ROOT folder with 3 .wars.  ROOT only has index.jsp in it.

**Comment by thebleucheese** [comment]
I just ran through the install process and I think we missed a step.  The readme assumes you're downloading and extracting to /opt/vectr.  This is evident by the docker-compose.yml configuration file's volume definitions.  

On the left side of the volume definitions they default to /opt/vectr in the release copy, but I had to change them to my directory where I downloaded and extracted the VECTR CE zip file (/home/ubuntu/vectr) to get things to work.

```yml
  mongo:
...
    volumes:
      - /home/ubuntu/vectr/dumpfiles:/opt/vectr/dumpfiles

  tomcat:
...
    volumes:
      - /home/ubuntu/vectr/wars:/usr/local/tomcat/webapps/
      - /home/ubuntu/vectr/config:/usr/local/tomcat/app_conf
      - /home/ubuntu/vectr/backup:/opt/vectr/backup/
      - /home/ubuntu/vectr/migrationlogs:/opt/vectr/migrationlogs/
      - /home/ubuntu/vectr/migrationbackups:/opt/vectr/migrationbackups

```

After this, everything was cool on my ubuntu 18.04 VM and vectr started and worked after doing docker-compose and going to 127.0.0.1:8081/sra-purpletools-webui/app.  I'm going to see if this docker-compose.yml file will work OK with relative paths so it doesn't need to be edited by end users.

**Comment by thebleucheese** [comment]
Following up on my post above this, relative paths work for the volumes in the yml files so that should be the easiest fix.

Modifying these files to the following fixed the problem for me on a fresh ubuntu 18.04 vm with docker ce and docker-compose installed.

***docker-compose.yml***
```yml
version: '2'

services:
  mongo:
    image: mongo:3.2.3
    network_mode: bridge
    volumes:
      - ./dumpfiles:/opt/vectr/dumpfiles

  tomcat:
    build:
      context: ./
    network_mode: bridge
    image: vectr_tomcat:latest
    volumes:
      - ./wars:/usr/local/tomcat/webapps/
      - ./config:/usr/local/tomcat/app_conf
      - ./backup:/opt/vectr/backup/
      - ./migrationlogs:/opt/vectr/migrationlogs/
      - ./migrationbackups:/opt/vectr/migrationbackups
    depends_on:
      - mongo
    links:
      - mongo:vectr-mongo
      - mongo:oauth2-mongo
```

***dev.yml***
```yml
version: '2'

services:
  mongo:
    ports:
      - "27018:27017"
    container_name: vectr_mongo_sandbox1
    volumes:
      - ./data/sandbox1:/data/db

  tomcat:
    container_name: vectr_tomcat_sandbox1
    ports:
      - "8081:8080"
```
